### PR TITLE
New version of "2.1.2. Jakarta EE 8 Platform Highlights" paragraph.

### PR DESCRIPTION
**Pull request by DmitriGit**
Hello Community,

 I have studied “Platform Highlights” paragraphs from “Java EE **6**”, “Java EE **7**” and “Java EE **8**” and produced the “Platform Highlights” for Jakarta 9, mantaining manner of expression and structure of previous versions to have the new one to be the logical continuation.

 If you agree, the content of the paragraph “Jakarta EE 9 Platform Highlights.” could be the following:

***************************************************************************************************
Jakarta EE 9 Platform Highlights.

The goal of the Jakarta EE 9 release is to deliver a set of specifications functionally similar to Jakarta EE 8 but in the new Jakarta EE 9 namespace jakarta.*.

In addition, the Jakarta EE 9 release removes a small set of specifications from Jakarta EE 8 that were old, optional, or deprecated in order to reduce the surface area of the APIs to ensure that it is easier for new vendors to enter the ecosystem – as well as reduce the burden on implementation, migration, and maintenance of these old APIs.

The following Jakarta EE Technologies were removed from the Jakarta EE Platform:

XML Registries 1.0
XML RPC 1.1
Deployment 1.7
Management 1.1
Distributed Interoperability (EJB 3.2 Core Specification, Chapter 10)
 
Aside from the removed technologies, some technologies in Jakarta EE 9 release are marked as optional. The reason for this is that some of the technologies originally included in Jakarta EE are no longer as relevant as they were when they were introduced to the platform. 

Platform Specification Project can decide to officially "remove" the "optional" feature from the Platform in the next (or beyond) releases.

The following technologies are optional:

Jakarta Enterprise Beans 3.2 and earlier entity beans and associated Jakarta Enterprise Beans QL
Jakarta Enterprise Beans 2.x API group
Jakarta Enterprise Web Services 2.0
Jakarta SOAP with Attachments 2.0
Jakarta Web Services Metadata 3.0
Jakarta XML Web Services 3.0
Jakarta XML Binding 3.0
***************************************************************************************************

### CODE REVIEW

**Comment by hussainnm** [comment]
Looks good. I will resolve the merge conflict

@ggam Can you take a look at this.

**Comment by ggam** [comment]
Very nice. Thanks a lot @DmitriGit

**Comment by DmitriGit** [comment]
> Very nice. Thanks a lot @DmitriGit

Thank you very much, Guillermo! I'm glad that my work is liked to you. :)

**Comment by hussainnm** [comment]
@DmitriGit have you signed the [ECA](https://www.eclipse.org/legal/ECA.php)? If not, please do so and also sign-off this commit with the same mail address.

**Comment by DmitriGit** [comment]
Yes, I have already created a user in ECA. My user's email address is the same of GitHub.
Dmitri.
    On Saturday, January 30, 2021, 08:47:47 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


@DmitriGit have you signed the ECA? If not, please do so and also sign-off this commit with the same mail address.

**Comment by hussainnm** [comment]
This commit needs to have a signed-off-by footer to pass the ECA.

See [Contributing via Git](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record) for more info.

You will need to fix the author field as well, i think it is currently your machine username and not github user name.

```
git config user.name "Dmitri Cherkas"
git config user.email "dmitricerkas@yahoo.com"
git commit --amend --sign-off --author="Dmitri Cherkas <dmitricerkas@yahoo.com>" --no-edit
git push --force-with-lease
```

**Comment by DmitriGit** [comment]
Hello Hussain,
I pushed changes taking into account your tips - thank you! Check, please.
I'm passing to work with images so. The new format of the images must be SVG, right? Do you have a design tool to suggest me for create SVG images?
Dmitri.


    On Sunday, January 31, 2021, 11:14:17 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


This commit needs to have a signed-off-by footer to pass the ECA.

See Contributing via Git for more info.

You will need to fix the author field as well, i think it is currently your machine username and not github user name.
git config user.name "Dmitri Cherkas"
git config user.email "dmitricerkas@yahoo.com"
git commit --amend --sign-off --author="Dmitri Cherkas <dmitricerkas@yahoo.com>" --no-edit
git push --force-with-lease

**Comment by DmitriGit** [comment]
Hello Hussain - don't worry - I just found a tool ! The images will be very-very nice ! :)
I'll send you tonight or tomorrow the first image in SVG format for evaluating and approval.
Dmitri.


    On Monday, February 1, 2021, 06:34:00 PM GMT+1, Dmitri Cerkas <dmitricerkas@yahoo.com> wrote:  
 
  Hello Hussain,
I pushed changes taking into account your tips - thank you! Check, please.
I'm passing to work with images so. The new format of the images must be SVG, right? Do you have a design tool to suggest me for create SVG images?
Dmitri.


    On Sunday, January 31, 2021, 11:14:17 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


This commit needs to have a signed-off-by footer to pass the ECA.

See Contributing via Git for more info.

You will need to fix the author field as well, i think it is currently your machine username and not github user name.
git config user.name "Dmitri Cherkas"
git config user.email "dmitricerkas@yahoo.com"
git commit --amend --sign-off --author="Dmitri Cherkas <dmitricerkas@yahoo.com>" --no-edit
git push --force-with-lease

**Comment by DmitriGit** [comment]
Hello Hussain,
take a look (see attachment) at a new (svg-) version of "Figure 1-1 Multitiered applications" of the paragraph "2.1.4. Distributed Multitiered Applications". 
Do you like it? :)
Dmitri.



    On Sunday, January 31, 2021, 11:14:17 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


Reopened #1.

**Comment by DmitriGit** [comment]
Hello Hussain, 
I started to push a new version of images (pushed Figure 1-1 and Figure 1-2). Can you confirm me that all is ok with committing this time?
Thank you,Dmitri.
    On Sunday, January 31, 2021, 11:14:17 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


Reopened #1.

**Comment by hussainnm** [comment]
For every commit you need to have the Signed-off-by footer in the message. You need to fix the last commit.

Next time you commit just add the `-s` to your commit command

`git commit -s -m "commit message" `

**Comment by DmitriGit** [comment]
I reversed the last commit and did a commit with "-s" flag. Then pushed. Check, please, if all is ok, Hussain...


    On Monday, February 8, 2021, 04:42:38 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


For every commit you need to have the Signed-off-by footer in the message. You need to fix the last commit.

Next time you commit just add the -s to your commit command

git commit -s -m "commit message"

**Comment by hussainnm** [comment]
See PR #2 on what is expected. As per Eclipse commit guidelines, every commit on the PR needs a signed-off by in the footer of the commit message even if it is a revert. 

This PR now has 5 commits, of which only 2 are needed. You can recreate the branch with just the required commit either via cherrypick or rebase. 

Using `git commit --amend --sign-off --no-edit` you can add sign-off to the last commit if you forgot to add the sign-off footer.

`git push --force-with-lease` allows you to push overriding changes on your branch if you have already pushed to remote.

**Comment by DmitriGit** [comment]
Sorry Hussain for the chaos with commits and thank you for help... As a wrote you some days ago - the last years I worked in a bank that used an old proprietary VCS...
But I promise you that I'll  close knowledge gaps about Git as soon as possible. Sorry again.
Ok, now I have 3 new pictures to commit. My Git's command-line sequence will be:
        git commit -s -m "commit message"
        git push

In this case I'll commit my changes correctly?
Thank you,Dmitri.
    On Monday, February 8, 2021, 06:18:56 PM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


See PR #2 on what is expected. As per Eclipse commit guidelines, every commit on the PR needs a signed-off by in the footer of the commit message even if it is a revert.

This PR now has 5 commits, of which only 2 are needed. You can recreate the branch with just the required commit either via cherrypick or rebase.

Using git commit --amend --sign-off --no-edit you can add sign-off to the last commit if you forgot to add the sign-off footer.

git push --force-with-lease allows you to push overriding changes on your branch if you have already pushed to remote.

**Comment by DmitriGit** [comment]
Hello Hussain,
I see that "Java EE 8" (and as a consequence the "Jakarta EE 9") has not figures "1-6", "1-7", "1-8" and "1-9" presented instead in "Java EE 6" and "Java EE 7" (see paragraphs "Java EE 6 APIs", "Java EE 7 APIs", "Java EE APIs" and "Jakarta EE APIs" respectively).
So, must I delete them from repository (from "JakartaEE_9\src\main\asciidoc\images" directory and then commit)? Or may be you want to preserve them for future needs?
Thank you,Dmitri.


    On Monday, February 8, 2021, 06:18:56 PM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


See PR #2 on what is expected. As per Eclipse commit guidelines, every commit on the PR needs a signed-off by in the footer of the commit message even if it is a revert.

This PR now has 5 commits, of which only 2 are needed. You can recreate the branch with just the required commit either via cherrypick or rebase.

Using git commit --amend --sign-off --no-edit you can add sign-off to the last commit if you forgot to add the sign-off footer.

git push --force-with-lease allows you to push overriding changes on your branch if you have already pushed to remote.

**Comment by hussainnm** [comment]
For now you can leave them as it is. The content is commented in overview008.adoc. If we decide to delete the content then we can remove the images along with it.

**Comment by DmitriGit** [comment]
Hello,
i'm finished to create a new version of images for the first four chapters. So I think that at the end of the next week we will have all images of the tutorial in a new format.
Have a nice weekend!Dmitri.
    On Friday, February 12, 2021, 02:44:06 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


For now you can leave them as it is. The content is commented in overview008.adoc. If we decide to delete the content then we can remove the images along with it.

**Comment by DmitriGit** [comment]
Hello Hussain,
only to keep you updated - I'm going forward with images, but its not as easy as I imagined. :)))
At now I have recreated 20 images of 37 total quantity.I'm trying to be as fast as possible.
I'll update you about progress start of next week.
Dmitri.


    On Friday, February 12, 2021, 02:44:06 AM GMT+1, Hussain <notifications@github.com> wrote:  
 
 


For now you can leave them as it is. The content is commented in overview008.adoc. If we decide to delete the content then we can remove the images along with it.

**Comment by hussainnm** [comment]
No hurry Dmitri, even I am making slow progress with the remaining chapters (only 15 more to go).

**Comment by ggam** [comment]
Fantastic @dmitrigit! The work to redo the images was started by varios
folks but nevera finished. I'm very pleased to know we're really near the
end of the journey this time :)

**Comment by DmitriGit** [comment]
Thank you team! :) 
Working with you is a real pleasure for me... :)



    On Friday, February 19, 2021, 08:08:14 PM GMT+1, Guillermo González de Agüero <notifications@github.com> wrote:  
 
 

Fantastic @dmitrigit! The work to redo the images was started by varios
folks but nevera finished. I'm very pleased to know we're really near the
end of the journey this time :)

**Comment by ggam** [comment]
Hi @DmitriGit. Just wondering, how is your work on the images going? In case you are unable to finish it, would you be able to upload what you already have?

**Comment by DmitriGit** [comment]
Hi, now I'm at "Figure 50-5" so I'm missing 20 drawings. So I think to finish all work by next Friday.Is it fine as a timing? May be I'll finish before Friday.

    On Sunday, March 14, 2021, 12:48:58 PM GMT+1, Guillermo González de Agüero ***@***.***> wrote:  
 
 


Hi @DmitriGit. Just wondering, how is your work on the images going? In case you are unable to finish it, would you be able to upload what you already have?

**Comment by ggam** [comment]
Thanks @DmitriGit. Any timing is fine :) I just wanted to make sure we don't missed the already done work, as has happened other times on this specific task.

Glad to see you are still working on it.

**Comment by DmitriGit** [comment]
Don't worry - if I make the commitment - I keep it always! :)Images come beautiful and, in case we need to change something - we have a full control on every point and on every line.
Thank you. :)

    On Sunday, March 14, 2021, 01:17:51 PM GMT+1, Guillermo González de Agüero ***@***.***> wrote:  
 
 


Thanks @DmitriGit. Any timing is fine :) I just wanted to make sure we don't missed the already done work, as has happened other times on this specific task.

Glad to see you are still working on it.

**Comment by DmitriGit** [comment]
Ok, now I'm missing 12 Figures. :)I think Friday can commit my work.
Dmitri.
    On Sunday, March 14, 2021, 01:03:28 PM GMT+1, Dmitri Cerkas ***@***.***> wrote:  
 
  Hi, now I'm at "Figure 50-5" so I'm missing 20 drawings. So I think to finish all work by next Friday.Is it fine as a timing? May be I'll finish before Friday.

    On Sunday, March 14, 2021, 12:48:58 PM GMT+1, Guillermo González de Agüero ***@***.***> wrote:  
 
 


Hi @DmitriGit. Just wondering, how is your work on the images going? In case you are unable to finish it, would you be able to upload what you already have?

**Comment by DmitriGit** [comment]
Hello Team,
I miss five pictures to finish: "56-2", "56-4", "58-2", "62_1" and "62_2". Start of the next week i'll commit all work (recreating completely images it's not so simple to predict exact delivery).
Only for show you the difference from old version to the new one, see in attachment Figure 50-6.
Dmitri.


    On Tuesday, March 16, 2021, 08:40:36 PM GMT+1, Dmitri Cerkas ***@***.***> wrote:  
 
  Ok, now I'm missing 12 Figures. :)I think Friday can commit my work.
Dmitri.
    On Sunday, March 14, 2021, 01:03:28 PM GMT+1, Dmitri Cerkas ***@***.***> wrote:  
 
  Hi, now I'm at "Figure 50-5" so I'm missing 20 drawings. So I think to finish all work by next Friday.Is it fine as a timing? May be I'll finish before Friday.

    On Sunday, March 14, 2021, 12:48:58 PM GMT+1, Guillermo González de Agüero ***@***.***> wrote:  
 
 


Hi @DmitriGit. Just wondering, how is your work on the images going? In case you are unable to finish it, would you be able to upload what you already have?

**Comment by ggam** [comment]
Can't wait for it.

Btw I think your attachment was lost.

**Comment by DmitriGit** [comment]
I think "github" mail server deletes attachments of incoming mails... Do you have another email?


    On Friday, March 19, 2021, 11:25:36 PM GMT+1, Guillermo González de Agüero ***@***.***> wrote:  
 
 

Can't wait for it.

Btw I think your attachment was lost.

**Comment by DmitriGit** [comment]
Ok, I can start to commit 64 images. I must create a Pull Request, right?
Dmitri.

    On Friday, March 19, 2021, 11:25:36 PM GMT+1, Guillermo González de Agüero ***@***.***> wrote:  
 
 

Can't wait for it.

Btw I think your attachment was lost.

**Comment by hussainnm** [comment]
Go ahead and create a PR in https://github.com/eclipse-ee4j/jakartaee-tutorial

**Comment by DmitriGit** [comment]
Hi Hussain,
work commited, PR created.
Let me know if all is ok.
Thank you,Dmitri.
    On Tuesday, March 23, 2021, 07:04:49 PM GMT+1, Hussain ***@***.***> wrote:  
 
 


Go ahead and create a PR in https://github.com/eclipse-ee4j/jakartaee-tutorial

**Comment by DmitriGit** [comment]
Hi Team,
new versions of "Figure 58-2" and "Figure 56-4" are pushed. Tomorrow and aftertomorrow I'll push the last two images and Errata Corrige of already pushed images.

Thank you,Dmitri.

    On Wednesday, March 24, 2021, 08:07:15 PM GMT+1, Dmitri Cerkas ***@***.***> wrote:  
 
  Hi Hussain,
work commited, PR created.
Let me know if all is ok.
Thank you,Dmitri.
    On Tuesday, March 23, 2021, 07:04:49 PM GMT+1, Hussain ***@***.***> wrote:  
 
 


Go ahead and create a PR in https://github.com/eclipse-ee4j/jakartaee-tutorial

**Comment by hussainnm** [comment]
I have merged the first commit by cherry-picking it. Closing this PR.

**Comment by DmitriGit** [comment]
Hi Team,
Errata Corrige of all images is completed, all changes are pushed.
I completed this activity. :)Anyway, if you'll find some errors and imperfections - I'll correct them. 
What the next can I do? :)
Dmitri.


    On Thursday, April 8, 2021, 08:47:42 PM GMT+2, Dmitri Cerkas ***@***.***> wrote:  
 
  Hi Team,
new versions of "Figure 58-2" and "Figure 56-4" are pushed. Tomorrow and aftertomorrow I'll push the last two images and Errata Corrige of already pushed images.

Thank you,Dmitri.

    On Wednesday, March 24, 2021, 08:07:15 PM GMT+1, Dmitri Cerkas ***@***.***> wrote:  
 
  Hi Hussain,
work commited, PR created.
Let me know if all is ok.
Thank you,Dmitri.
    On Tuesday, March 23, 2021, 07:04:49 PM GMT+1, Hussain ***@***.***> wrote:  
 
 


Go ahead and create a PR in https://github.com/eclipse-ee4j/jakartaee-tutorial

**Pull request closed without merging**
